/**
 * OG card generator.
 *
 * Approach: SVG template rendered to PNG via `@resvg/resvg-js`. We
 * deliberately do NOT use satori here — satori needs embedded TTF/OTF
 * font data and we ship WOFF2 (which satori can't read). resvg's
 * built-in text rendering uses the system font stack; on Linux servers
 * (and in the Docker image we deploy to) that's fine. On Windows dev
 * boxes resvg uses whatever's installed, which is a non-issue since OG
 * images are generated by the deployed server.
 *
 * The card is 1200x630 — the OG spec's blessed size. Dark bg, green
 * accent dot, sans title + description, mono `last_verified` date.
 */
import { Resvg } from '@resvg/resvg-js';

const WIDTH = 1200;
const HEIGHT = 630;

const BG = '#0a0a0a';
const CARD_BG = '#111111';
const CARD_BORDER = '#2a2a2a';
const ACCENT = '#10b981';
const TEXT = '#f5f5f5';
const TEXT_MUTED = '#a3a3a3';

interface OgCardArgs {
  title: string;
  category: string;
  lastVerified: string; // YYYY-MM-DD
}

/**
 * XML-escape untrusted text. Title and category come from content
 * frontmatter, which is authored by us, but any `<` / `&` in legit copy
 * (e.g. "Cookies & storage") still needs escaping.
 */
function xmlEscape(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Wrap a title into up to 2 lines of approx 28 chars each. Satori-style
 * word wrap — crude, but good enough for OG cards where titles are
 * already short.
 */
function wrapTitle(title: string, maxCharsPerLine = 28): string[] {
  const words = title.split(/\s+/);
  const lines: string[] = [];
  let current = '';
  for (const w of words) {
    const candidate = current ? `${current} ${w}` : w;
    if (candidate.length > maxCharsPerLine && current) {
      lines.push(current);
      current = w;
    } else {
      current = candidate;
    }
    if (lines.length >= 2) break;
  }
  if (current && lines.length < 2) lines.push(current);
  // Truncate overflow
  if (words.join(' ').length > maxCharsPerLine * 2) {
    const last = lines[lines.length - 1];
    if (last) lines[lines.length - 1] = `${last.slice(0, maxCharsPerLine - 1)}…`;
  }
  return lines;
}

export function buildOgSvg({ title, category, lastVerified }: OgCardArgs): string {
  const titleLines = wrapTitle(title);
  const escapedCategory = xmlEscape(category);
  const escapedDate = xmlEscape(lastVerified);
  const titleTspans = titleLines
    .map(
      (line, idx) =>
        `<tspan x="80" dy="${idx === 0 ? 0 : 90}">${xmlEscape(line)}</tspan>`,
    )
    .join('');

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg width="${WIDTH}" height="${HEIGHT}" xmlns="http://www.w3.org/2000/svg">
  <rect width="${WIDTH}" height="${HEIGHT}" fill="${BG}"/>
  <rect x="40" y="40" width="${WIDTH - 80}" height="${HEIGHT - 80}" rx="16" fill="${CARD_BG}" stroke="${CARD_BORDER}" stroke-width="2"/>
  <text x="80" y="130" font-family="sans-serif" font-size="24" fill="${ACCENT}" font-weight="600">privacy.whattheflip.lol</text>
  <text x="80" y="170" font-family="sans-serif" font-size="20" fill="${TEXT_MUTED}" font-weight="500" text-transform="uppercase">${escapedCategory}</text>
  <text y="280" font-family="sans-serif" font-size="72" fill="${TEXT}" font-weight="700">${titleTspans}</text>
  <circle cx="80" cy="540" r="8" fill="${ACCENT}"/>
  <text x="100" y="548" font-family="monospace" font-size="20" fill="${TEXT_MUTED}">Last verified ${escapedDate}</text>
</svg>`;
}

export function renderOgPng(args: OgCardArgs): Uint8Array {
  const svg = buildOgSvg(args);
  const resvg = new Resvg(svg, { background: BG });
  return resvg.render().asPng();
}
